<a href="https://colab.research.google.com/github/hyperkraz/MAT421/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**HW5**

***Gram-Schmidt and QR Decomposition***

First we take a look at NumPy's built-in QR Decomposition function:

In [19]:
import numpy as np

arr = np.array([[5, 11, -15], [12, 34, -51], [-24, -43, 92]], dtype=np.int32)
array = np.array([[5, 11, -15], [12, 34, -51], [-24, -43, 92]], dtype=np.int32)

In [20]:
q, r = np.linalg.qr(arr)

print('\nQ: \n', q)
print('\nR: \n', r)

print ('\n')

print ('Q * R: ')

print (np.dot(q, r))


Q: 
 [[-0.18318583 -0.08610905  0.97929984]
 [-0.43964598 -0.88381371 -0.15995231]
 [ 0.87929197 -0.45984624  0.12404465]]

R: 
 [[-27.29468813 -54.77256208 106.06459346]
 [  0.         -11.22347731   4.06028083]
 [  0.           0.           4.88017756]]


Q * R: 
[[  5.  11. -15.]
 [ 12.  34. -51.]
 [-24. -43.  92.]]


As it can be seen, the built-in function works very well as we can then take the product of both the orthogonal matrix Q and the upper triangular matrix R and it will result in the original matrix.

Now we can take a look at a custom function that attempts to do the same:

In [21]:
def GrammyS(A):
    
    Q = np.zeros(A.shape)

    R = np.zeros((A.shape[1], A.shape[1]))
    
    
    for i in range(0, A.shape[1]):

        R[i, i] = np.sqrt(np.dot(A[:, i], A[:, i]))
        Q[:, i] = A[:, i] / R[i, i]
        
        for j in range(i+1, A.shape[1]):
            
            R[i, j] = np.dot(Q[:, i], A[:, j])
            A[:, j] = A[:, j] - R[i, j] * Q[:, i]
    
    return Q, R


In [22]:
Q, R = GrammyS(array)

print('\nQ: \n', Q)
print('\nR: \n', R)

print ('\n')

print ('Q * R: ')

print (np.dot(Q, R))



Q: 
 [[ 0.18318583  0.          1.        ]
 [ 0.43964598  0.87415728  0.        ]
 [-0.87929197  0.48564293  0.        ]]

R: 
 [[  27.29468813   54.77256208 -106.06459346]
 [   0.           10.29563014   -3.98227204]
 [   0.            0.            4.        ]]


Q * R: 
[[  5.          10.03355705 -15.4295302 ]
 [ 12.          33.08053691 -50.11200456]
 [-24.         -43.16107383  91.3277827 ]]


The above function is similar except it results in reversed poisitive and negative signs for some of the values in matrices Q and R. Once the product of Q and R is calculated, however, the result is very close to the original matrix.

Now we can show another custom function that attempts the QR Decomposition except done in a different way (note the use of linalg.norm from NumPy in order to normalize):

In [23]:
def QR_fact(A):
  
    m, n = A.shape
    
    R = np.zeros((n, n))
    Q = np.zeros((m, n))
    

    for j in range(n):

        x = A[:, j]

        for i in range(j - 1):
            
            q = Q[:, i]
            
            R[i, j] = q.dot(x)
            
            x = x - R[i, j] * q

        length = np.linalg.norm(x)
        
        R[j, j] = length
        Q[:, j] = x / length
        

    return Q, R

QR_fact(arr)

Q2, R2 = QR_fact(arr)

print('\nQ: \n', Q2)
print('\nR: \n', R2)

print ('\n')

print ('Q * R: ')

print (np.dot(Q2, R2))


Q: 
 [[ 0.18318583  0.19674251  0.69774108]
 [ 0.43964598  0.6081132  -0.68822643]
 [-0.87929197 -0.76908434 -0.19875049]]

R: 
 [[  27.29468813    0.         -106.06459346]
 [   0.           55.91064299    0.        ]
 [   0.            0.            6.34838668]]


Q * R: 
[[  5.  11. -15.]
 [ 12.  34. -51.]
 [-24. -43.  92.]]


It can be observed that both the orthogonal matrix Q and the upper triangular matrix R are vastly different from the ones computed by NumPy's built-in QR Decomposition function. But, the product of Q and R here produce the exact same matrix as the one that we started out with.

***Eigenvalues and Eigenvectors***

As shown above, we can make use of NumPy's built-in functions to calculate many things.

Another example of this is NumPy's built-in linalg.eig function that can be used to calculate eigenvectors and the corresponding eigenvalues:


In [24]:
somearray = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

l, x = np.linalg.eig(somearray)

print('Eigenvalue: ', l)
print('\nEigenvector: ', x)

print ('\n\nA * x: ')

print (np.dot(somearray, x))

print ('\nλ * x: ')

print (np.multiply(l, x))

Eigenvalue:  [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

Eigenvector:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


A * x: 
[[-3.73863537e+00  8.77649763e-01 -3.88578059e-16]
 [-8.46653421e+00  9.68877101e-02 -7.77156117e-16]
 [-1.31944331e+01 -6.83874343e-01 -7.21644966e-16]]

λ * x: 
[[-3.73863537e+00  8.77649763e-01 -3.98417052e-16]
 [-8.46653421e+00  9.68877101e-02  7.96834105e-16]
 [-1.31944331e+01 -6.83874343e-01 -3.98417052e-16]]


As demonstrated above, we can compute the dot product of the resulting eigenvector and the original matrix and compare it to the product of the eigenvalue (lambda) and the eigenvector and see that the result is the same.